// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLuedZvBWdpdRPstQQSWgyIX7Oimd2zKc',
    appId: '1:750102190435:web:0bcde91f0022eb0dca9b56',
    messagingSenderId: '750102190435',
    projectId: 'test-8c9cd',
    authDomain: 'test-8c9cd.firebaseapp.com',
    databaseURL: 'https://test-8c9cd-default-rtdb.firebaseio.com',
    storageBucket: 'test-8c9cd.appspot.com',
    measurementId: 'G-DP7ZH9ELFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGRdxYyc0PeZCXKGOGDOSuHsnwtwwfIEc',
    appId: '1:750102190435:android:42b08cbe8da3421fca9b56',
    messagingSenderId: '750102190435',
    projectId: 'test-8c9cd',
    databaseURL: 'https://test-8c9cd-default-rtdb.firebaseio.com',
    storageBucket: 'test-8c9cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9sae9fhLJyIOg-3Zdx2zyMxhgU3FrCyI',
    appId: '1:750102190435:ios:0de6609ec8b68ac3ca9b56',
    messagingSenderId: '750102190435',
    projectId: 'test-8c9cd',
    databaseURL: 'https://test-8c9cd-default-rtdb.firebaseio.com',
    storageBucket: 'test-8c9cd.appspot.com',
    androidClientId: '750102190435-969d9bmn67g7tfa9sfbbrt6ro36bi0s4.apps.googleusercontent.com',
    iosClientId: '750102190435-0bptu0p6eachrlcaurq7ectrt36rrm6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9sae9fhLJyIOg-3Zdx2zyMxhgU3FrCyI',
    appId: '1:750102190435:ios:0de6609ec8b68ac3ca9b56',
    messagingSenderId: '750102190435',
    projectId: 'test-8c9cd',
    databaseURL: 'https://test-8c9cd-default-rtdb.firebaseio.com',
    storageBucket: 'test-8c9cd.appspot.com',
    androidClientId: '750102190435-969d9bmn67g7tfa9sfbbrt6ro36bi0s4.apps.googleusercontent.com',
    iosClientId: '750102190435-0bptu0p6eachrlcaurq7ectrt36rrm6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpaJXldXJb2tWCWwwLtyoDjeSJQIMnCXg',
    appId: '1:750102190435:web:0c24dbbb8bffc8f0ca9b56',
    messagingSenderId: '750102190435',
    projectId: 'test-8c9cd',
    authDomain: 'test-8c9cd.firebaseapp.com',
    databaseURL: 'https://test-8c9cd-default-rtdb.firebaseio.com',
    storageBucket: 'test-8c9cd.appspot.com',
    measurementId: 'G-CN2GJRKD2Q',
  );

}